### PR TITLE
#93 adds status to houses migration

### LINKED ISSUE #93: Current ad status of houses
People want to see active ads instead of 30 years old an ad without any update, so we should add a feature that shows the status of house (ad).

## Implementation

In the model of House (`House.rb`) will have:

```ruby
class House < ApplicationRecord
  # ...
  enum status: { active: 'active', archived: 'archived' }
  # ...
end
```
1. Should use `string` instead of `integer` because `integer` makes hard to understand the context
2. Solve the data integrity issue with database specific `ENUM()` data types.

*P.S. Thanks to Eduardo Figarola's article (link in the sources section)*

## Rails, PostgreSQL and `ENUM()`

<details>
  <summary>An example of migration file</summary>

  ```ruby
  class AddStatusToHouses < ActiveRecord::Migration[5.2]
    def up
      execute <<-SQL
        CREATE TYPE house_statuses AS ENUM ('active', 'archived');
      SQL

      add_column :houses, :status, :house_statuses
    end

    def down
      remove_column :houses, :status, :house_statuses

      execute <<-SQL
        DROP TYPE house_statuses;
      SQL
    end
  end
  ```
</details>

Using this migration file causes to return an exception in the `schema.rb`

```ruby
# ...
# Could not dump table "houses" because of following StandardError
#   Unknown type 'house_statuses' for column 'status'
# ...
```

### Source about Rails, PostgreSQL and `ENUM()`

I read different sources

* [Enums with Rails & ActiveRecord: an improved way](https://sipsandbits.com/2018/04/30/using-database-native-enums-with-rails/)
* [Postgres enums with Rails](https://dev.to/amplifr/postgres-enums-with-rails-4ld0)
* [Enumerated Types with ActiveRecord and PostgreSQL](https://www.sitepoint.com/enumerated-types-with-activerecord-and-postgresql/)

### PR DESCRIPTION
**Pull request by noloman**
Fixes #93

### CODE REVIEW

File: db/migrate/20190503071942_add_status_to_houses.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+class AddStatusToHouses < ActiveRecord::Migration[5.2]
```
Comment (BerkhanBerkdemir) [inline db/migrate/20190503071942_add_status_to_houses.rb]: * use `change` instead of `up` and `down`
* we want to make it inactive since we'll manually activate them
* also, we can keep the record of when the ad was archived or activated

```ruby
def change
  add_column :houses, :houses_status, :integer, default: 0
end
```

File: app/models/house.rb [hunk 2]
```diff
@@ -18,6 +18,10 @@ class House < ApplicationRecord
   validates :available_at, presence: true, at_future: true
 
   enum preferred_gender: %i[either female male]
+  enum status: {
```
Comment (BerkhanBerkdemir) [inline app/models/house.rb]: you don't need to say `{active: 1, archived: 0}`. Use `%i[archived active]`.

*P.S. the order is important*

File: db/migrate/20190503071942_add_status_to_houses.rb (hunk 1 above)
Comment (noloman) [reply db/migrate/20190503071942_add_status_to_houses.rb]: perfect, I will do that and create some tests. I just wanted you to see the changes but this is not ready yet for merging

Comment (noloman) [reply db/migrate/20190503071942_add_status_to_houses.rb]: Thanks!

File: app/models/house.rb (hunk 2 above)
Comment (noloman) [reply app/models/house.rb]: thanks, this is a good point

**Comment by noloman** [comment]
> Let's delete `.ruby-version`, which we use `ruby` on Gemfile, and `yarn.lock`. I don't want to update JavaScript things for now.

Sure. Should I just add them to the `gitignore` file?

**Comment by BerkhanBerkdemir** [comment]
> > Let's delete `.ruby-version`, which we use `ruby` on Gemfile, and `yarn.lock`. I don't want to update JavaScript things for now.
> 
> Sure. Should I just add them to the `gitignore` file?

No, we need `yarn.lock`. There is no difference between `Gemfile.lock` and `yarn.lock`. We use `ruby ~> 2.5.3` on `Gemfile`, so we don't need to have `.ruby-version`.

**Comment by noloman** [comment]
> Let's delete `.ruby-version`, which we use `ruby` on Gemfile, and `yarn.lock`. I don't want to update JavaScript things for now.

But isn't it better to add it to the .gitignore? because I'm using rbenv locally and I need this file, as we use Ruby 2.5.3 and my global version is 2.6.3

**Comment by BerkhanBerkdemir** [comment]
> > Let's delete `.ruby-version`, which we use `ruby` on Gemfile, and `yarn.lock`. I don't want to update JavaScript things for now.
> 
> But isn't it better to add it to the .gitignore? because I'm using rbenv locally and I need this file, as we use Ruby 2.5.3 and my global version is 2.6.3

Make sense :+1: I didn't think that you use rbenv with local ruby version. So, yeah, leave it there :laughing:

File: spec/models/house_spec.rb [hunk 3]
```diff
@@ -22,6 +22,22 @@
     expect(subject).to have_one(:checkbox).dependent(:destroy)
   end
 
+  context 'status' do
+    it 'has an inactive status by default' do
```
Comment (BerkhanBerkdemir) [inline spec/models/house_spec.rb]: That's weird since it says **inactive status by default**, but expecting to get `active`

**Comment by BerkhanBerkdemir** [comment]
Hey @noloman,

Can I ask you to remove `yarn.lock` changes, and resolve [that](https://github.com/magara/magara/pull/108#discussion_r280997475)?

After that you can squash and merge it :+1:

File: spec/models/house_spec.rb (hunk 3 above)
Comment (noloman) [reply spec/models/house_spec.rb]: that's what I thought we'd do: having the ads in an inactive status by default

Comment (noloman) [reply spec/models/house_spec.rb]: yes, my bad: I think we said `inactive` by default, didn't we?
